"""initial eai schema

Revision ID: 8efcb5f13881
Revises: 
Create Date: 2026-08-03 03:15:18.087479
"""
from alembic import op
import sqlalchemy as sa


revision = '8efcb5f13881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('resumable', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('cross_company_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.String(length=64), nullable=False),
    sa.Column('theme_name_en', sa.String(length=256), nullable=False),
    sa.Column('theme_name_ko', sa.String(length=256), nullable=False),
    sa.Column('analysis_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme_score', sa.Float(), nullable=True),
    sa.Column('score_status', sa.String(length=32), nullable=False),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('maturity_label', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('score_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_company_themes_theme_id'), 'cross_company_themes', ['theme_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=48), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.String(length=64), nullable=False),
    sa.Column('exact_quote_en', sa.Text(), nullable=False),
    sa.Column('translation_ko', sa.Text(), nullable=True),
    sa.Column('quote_start_offset', sa.Integer(), nullable=True),
    sa.Column('quote_end_offset', sa.Integer(), nullable=True),
    sa.Column('paragraph_hash', sa.String(length=64), nullable=True),
    sa.Column('evidence_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_claim_id'), 'evidence_links', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_paragraph_id'), 'evidence_links', ['paragraph_id'], unique=False)
    op.create_table('model_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('ontology_version', sa.String(length=16), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('provider_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('classification_rule_version', sa.String(length=16), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_version', sa.String(length=16), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_ko', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_ontology_version'), 'topics', ['ontology_version'], unique=False)
    op.create_index(op.f('ix_topics_topic_id'), 'topics', ['topic_id'], unique=False)
    op.create_table('user_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('corrected_value', sa.JSON(), nullable=True),
    sa.Column('corrected_by', sa.String(length=64), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('ontology_version', sa.String(length=16), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_signal_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'role', name='uq_company_role')
    )
    op.create_table('company_universe_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('universe_type', sa.String(length=16), nullable=False),
    sa.Column('tracked_quarters', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_value_chain_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('verification_method', sa.String(length=24), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('numeric_check', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guidance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('guidance_mid', sa.Float(), nullable=True),
    sa.Column('guidance_low', sa.Float(), nullable=True),
    sa.Column('guidance_high', sa.Float(), nullable=True),
    sa.Column('consensus', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_metrics_ticker'), 'guidance_metrics', ['ticker'], unique=False)
    op.create_table('incremental_information_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_version', sa.String(length=16), nullable=False),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_row_id', sa.Integer(), nullable=True),
    sa.Column('investment_theme', sa.String(length=256), nullable=False),
    sa.Column('conviction', sa.String(length=16), nullable=False),
    sa.Column('narrative_confirmation_status', sa.String(length=48), nullable=True),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('maturity_label', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_row_id'], ['cross_company_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarterly_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('from_period', sa.String(length=16), nullable=False),
    sa.Column('to_period', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarterly_comparisons_ticker'), 'quarterly_comparisons', ['ticker'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_checksum'), 'source_documents', ['checksum'], unique=False)
    op.create_table('theme_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_row_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weighted', sa.Float(), nullable=True),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['theme_row_id'], ['cross_company_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=True),
    sa.Column('calendar_quarter', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.String(length=32), nullable=True),
    sa.Column('event_date', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_quarter', name='uq_transcript_period')
    )
    op.create_index(op.f('ix_transcript_documents_ticker'), 'transcript_documents', ['ticker'], unique=False)
    op.create_table('universe_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('gaap_or_non_gaap', sa.String(length=16), nullable=True),
    sa.Column('actual_or_guidance', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.String(length=32), nullable=True),
    sa.Column('period_end', sa.String(length=32), nullable=True),
    sa.Column('comparison_basis', sa.String(length=32), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=32), nullable=True),
    sa.Column('source_paragraph_id', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metrics_ticker'), 'financial_metrics', ['ticker'], unique=False)
    op.create_table('transcript_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('raw_storage_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_versions_checksum'), 'transcript_versions', ['checksum'], unique=False)
    op.create_table('call_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_summaries_ticker'), 'call_summaries', ['ticker'], unique=False)
    op.create_table('chunk_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('chunk_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('raw_llm_output', sa.JSON(), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('ontology_version', sa.String(length=16), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=24), nullable=False),
    sa.Column('speaker_role', sa.String(length=24), nullable=True),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('topic_category', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('management_initiated', sa.Boolean(), nullable=False),
    sa.Column('analyst_initiated', sa.Boolean(), nullable=False),
    sa.Column('numeric_support', sa.Boolean(), nullable=False),
    sa.Column('guidance_related', sa.Boolean(), nullable=False),
    sa.Column('insufficient_evidence', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_mentions_ticker'), 'topic_mentions', ['ticker'], unique=False)
    op.create_index(op.f('ix_topic_mentions_topic_id'), 'topic_mentions', ['topic_id'], unique=False)
    op.create_table('transcript_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.String(length=64), nullable=False),
    sa.Column('section_type', sa.String(length=24), nullable=False),
    sa.Column('speaker_name', sa.String(length=128), nullable=True),
    sa.Column('speaker_role', sa.String(length=24), nullable=True),
    sa.Column('speaker_company', sa.String(length=128), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('exact_text_en', sa.Text(), nullable=False),
    sa.Column('normalized_text_en', sa.Text(), nullable=False),
    sa.Column('preceding_question_id', sa.String(length=64), nullable=True),
    sa.Column('answer_to_question_id', sa.String(length=64), nullable=True),
    sa.Column('paragraph_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_paragraphs_paragraph_hash'), 'transcript_paragraphs', ['paragraph_hash'], unique=False)
    op.create_index(op.f('ix_transcript_paragraphs_paragraph_id'), 'transcript_paragraphs', ['paragraph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_paragraphs_paragraph_id'), table_name='transcript_paragraphs')
    op.drop_index(op.f('ix_transcript_paragraphs_paragraph_hash'), table_name='transcript_paragraphs')
    op.drop_table('transcript_paragraphs')
    op.drop_index(op.f('ix_topic_mentions_topic_id'), table_name='topic_mentions')
    op.drop_index(op.f('ix_topic_mentions_ticker'), table_name='topic_mentions')
    op.drop_table('topic_mentions')
    op.drop_table('speakers')
    op.drop_table('chunk_analysis')
    op.drop_index(op.f('ix_call_summaries_ticker'), table_name='call_summaries')
    op.drop_table('call_summaries')
    op.drop_index(op.f('ix_transcript_versions_checksum'), table_name='transcript_versions')
    op.drop_table('transcript_versions')
    op.drop_index(op.f('ix_financial_metrics_ticker'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_table('universe_change_history')
    op.drop_index(op.f('ix_transcript_documents_ticker'), table_name='transcript_documents')
    op.drop_table('transcript_documents')
    op.drop_table('theme_components')
    op.drop_index(op.f('ix_source_documents_checksum'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_quarterly_comparisons_ticker'), table_name='quarterly_comparisons')
    op.drop_table('quarterly_comparisons')
    op.drop_table('investment_themes')
    op.drop_table('incremental_information_scores')
    op.drop_index(op.f('ix_guidance_metrics_ticker'), table_name='guidance_metrics')
    op.drop_table('guidance_metrics')
    op.drop_table('evidence_verifications')
    op.drop_table('company_value_chain_positions')
    op.drop_table('company_universe_types')
    op.drop_table('company_signal_roles')
    op.drop_table('watchlists')
    op.drop_table('user_corrections')
    op.drop_index(op.f('ix_topics_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_ontology_version'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('score_versions')
    op.drop_table('provider_errors')
    op.drop_table('prompt_versions')
    op.drop_table('ontology_versions')
    op.drop_table('model_usage')
    op.drop_index(op.f('ix_evidence_links_paragraph_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_claim_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_cross_company_themes_theme_id'), table_name='cross_company_themes')
    op.drop_table('cross_company_themes')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
